### ISSUE TITLE
ci: this repo has no CI at all — a test has been failing to compile since 2024

### ISSUE THREAD

**Issue by hsinatfootprintai** [FootprintAI/grandturks-client#15]
There is no `.github/` directory in this repository. No workflow builds it, tests it, vets it, or publishes it.

## Evidence that this is not theoretical

`pkg/encryption/aes_test.go` **does not compile**, on `main`, today:

```
# github.com/footprintai/grandturks-client/v2/pkg/encryption
pkg/encryption/aes_test.go:16:9: undefined: aesKey
pkg/encryption/aes_test.go:22:23: not enough arguments in call to NewAESEncryptor
	have (unknown type)
	want (cipher.Block, string)
pkg/encryption/aes_test.go:23:29: e.EncodeStr undefined (type aesEncryptor has no field or method EncodeStr)
pkg/encryption/aes_test.go:26:21: e.DecodeStr undefined (type aesEncryptor has no field or method DecodeStr)
FAIL	github.com/footprintai/grandturks-client/v2/pkg/encryption [build failed]
```

The file was last touched in `6e439b9` (2024-05-14). So the production signature of `NewAESEncryptor` changed under it and its tests have been dead ever since, with nothing to say so. Tracked separately as the defect it is — see the linked issue.

`go build ./...` passes and the other two packages pass, so this is the only current casualty. That is the point: nobody knows that without checking by hand.

## Why it matters more than usual for this repo

This module **is** the kafeido CLI. `grandturks`' `app/kafeido/cli/main.go` builds its root command from here; the equivalent files in that repo are commented-out dead duplicates (FootprintAI/grandturks#902). So every command an operator runs is code in this repo, and none of it is gated.

Related, from the grandturks side:
- no lane there builds or publishes the CLI either (FootprintAI/grandturks#902)
- the CLI is unreleased since 2024 — `v2.2.1` and `v2.3.0+rc0` carry binaries, grandturks' `v2.4.x` releases carry zero assets
- it self-reports `version:2.3.0+rc0`, because the version string comes from this module

## What would close this

A minimal lane is enough to be worth having:

```yaml
- go build ./...
- go vet ./...
- go test ./...
```

`go test ./...` is red today, so either the linked defect lands first, or the lane goes in alongside its fix.

Found while opening #14 (FootprintAI/grandturks#901), which had no CI to gate on — that PR's evidence is a local run, which is exactly the thing this issue is about.

**Comment by hsinatfootprintai** [comment]
agent-ccbbebd8-opus is starting processing it

**Comment by hsinatfootprintai** [comment]
PR: https://github.com/FootprintAI/grandturks-client/pull/26 (agent-ccbbebd8-opus)

Stacked on #24 (the #16 fix) and targeted at that branch, so the lane is green on its own run rather than green-because-narrowed: https://github.com/FootprintAI/grandturks-client/actions/runs/31997640521 — `build-vet-test  pass  1m43s`, the first CI run in this repository.

It was also verified to go **red**: the same workflow over unfixed main failed at `go vet` with `undefined: aesKey` (https://github.com/FootprintAI/grandturks-client/actions/runs/31997495948). The temporary PR used for that proof is closed and its branch deleted.

Merge #24 first; this one retargets to main automatically.
